### ISSUE TITLE
unified_job_template error when different objects have the same name

### ISSUE THREAD

**Issue by fvzwieten** [redhat-cop/automate_tower_genie_collections#330] opened 2022-07-14 19:30 UTC
I have a project named "Azure" and an inventory source named "Azure". In this case the following yml errors out because it returns 2 items where 1 is expected:

  workflow_nodes:
  - identifier: node401
    all_parents_must_converge: true
    unified_job_template:
      inventory:
        organization:
          name: '{{ org_name }}'
      name: Azure
      type: inventory_source

**Comment by sean-m-sullivan** [comment] 2022-07-14 19:55
The controller configuration is an implmentation of awx.awx or ansible.controller. 
The issue is here
https://github.com/ansible/awx/blob/84d7fa882d1701c2c74af7b7d410e3b9c2af20ae/awx_collection/plugins/modules/workflow_job_template.py#L504

It looks for all Unified job templates in the stated org, and returns results. It expects unique names. 

You can either supply the ID from the unified job template page
api/v2/unified_job_templates/?name__contains=Azure
or Change the project name to Azure Project, and Azure inventory, to differentiate them.

**Comment by fvzwieten** [comment] 2022-07-14 20:34
Yes, this is what I did, but only after staring at my screen for a few hours bewildered as to what could be the issue. Because I specify the inventory_source type, I expect it would filter on those..

**Comment by sean-m-sullivan** [comment] 2022-07-30 05:34
See https://github.com/ansible/awx/pull/12597 for a fix, they should review and merge it in the coming week.

**Comment by sean-m-sullivan** [comment] 2022-08-11 15:06
@fvzwieten It is merged in awx.awx as a fix if you want to compile a dev version of it to use :)
I'm closing this, as the PR is merged and its compatible with our roles, just needs to wait on releases from the ansible teams

**Closed as completed by sean-m-sullivan** 2022-08-11 15:06 UTC
