### ISSUE TITLE
"input_inventories" parameter does not exist for inventories

### ISSUE THREAD

**Issue by jpcarmona** [redhat-cop/automate_tower_genie_collections#585] opened 2023-04-25 11:23 UTC
# Summary

Hello again,
Is it possible that the "input_inventories" parameter should not exist for the role inventory?
https://console.redhat.com/ansible/automation-hub/repo/published/ansible/controller/content/module/inventory/?version=4.3.0

This parameter does not appear in the awx.awx and ansible.controller collections:
https://docs.ansible.com/ansible/latest/collections/awx/awx/inventory_module.html#ansible-collections-awx-awx-inventory-module
https://console.redhat.com/ansible/automation-hub/repo/published/ansible/controller/content/module/inventory/?version=4.3.0

# Issue Type

- Bug Report

**Comment by djdanielsson** [comment] 2023-04-25 12:59
interesting, so for this one I do see it in the code but not in the docs. https://github.com/ansible/awx/blob/2ce9440bab6f14c0eb2f1b85206f1f92dc88fe0d/awx_collection/plugins/modules/inventory.py#L68

**Comment by sean-m-sullivan** [comment] 2023-04-26 00:54
This was added in 22.0.0 3 weeks ago, its in the latest awx.awx, If you look at the docs page it was last built when ansible 7.0 released, which was version 21.14.0, and ansible.controller was released 6 months ago. 

The PR to add it is here
https://github.com/ansible/awx/pull/13525

We commonly add things to the roles and keep up to date with the awx collection, as it allows us to test and make sure things are ready for when the next version of AAP drops.

**Comment by sean-m-sullivan** [comment] 2023-04-26 01:10
Closing as it was not a bug

**Closed as completed by sean-m-sullivan** 2023-04-26 01:10 UTC
Labels: bug

**Comment by joeashcraft** [comment] 2023-06-09 21:58
if you want to use the Community Collection "awx.awx" and not the Red Hat Certified Collection "ansible.controller" (which, at this time is 4.3.0 which does not have input_inventories...), try using the EE "ee-minimal-rhel8" instead of the default "ee-supported-rhel8"
