### ISSUE TITLE
Asynchronous configuration breaks the order of the applied settings

### ISSUE THREAD

**Issue by ogajduse** [redhat-cop/automate_tower_genie_collections#388] opened 2022-10-18 14:55 UTC
We have the following configuration for our AAP.
```yaml
---
controller_settings:
  settings:
    - name: AUTH_LDAP_SERVER_URI
      value: "ldap://ldap.server.acme.com"
    - name: AUTH_LDAP_USER_DN_TEMPLATE
      value: "uid=%(user)s,ou=Users,dc=acme,dc=com"
    - name: AUTH_LDAP_GROUP_SEARCH
      value: "['dc=acme,dc=com', 'SCOPE_SUBTREE', '(objectClass=AcmeLdapGroup)']"
    - name: AUTH_LDAP_GROUP_TYPE  # <------
      value: "GroupOfUniqueNamesType"
    - name: AUTH_LDAP_USER_SEARCH
      value: "['OU=Users,DC=acme,DC=com', 'SCOPE_SUBTREE', '(cn=%(user)s)']"
    - name: AUTH_LDAP_START_TLS
      value: true
    - name: AUTH_LDAP_GROUP_TYPE_PARAMS  # <------
      value: {}
```

As the `settings` role is asynchronous, the order in which the settings are applied is not guaranteed. In this case, there are two settings where `AUTH_LDAP_GROUP_TYPE` has to be configured first before `AUTH_LDAP_GROUP_TYPE_PARAMS` is configured. Otherwise, we are getting error messages
`Missing required parameters in AUTH_LDAP_GROUP_TYPE_PARAMS.`
`The current value "'MemberDNGroupType'" for setting "AUTH_LDAP_GROUP_TYPE" is invalid.`

Currently, I can think of a solution where I invoke the `settings` role twice, first I give it the single setting (AUTH_LDAP_GROUP_TYPE) in a list and then I invoke the role again, giving it the rest of the settings.

Or if the role would allow, I would turn the async configuration off so all settings are applied sequentially.

I would like to hear the maintainer's thoughts on this.

**Comment by ogajduse** [comment] 2022-10-18 14:55
@bherrin3 @rdrazny

**Comment by sean-m-sullivan** [comment] 2022-10-19 14:39
We will look at this as the role should loop only once the way you put the code. 

This may be module level. 

We are out at Ansiblefest this week, so I will try to get to this soon.

**Comment by ogajduse** [comment] 2022-10-19 15:46
Thank you for your feedback @sean-m-sullivan. As you stated, the role loops only once the way we put the code, agreed.
Just to be clear, I just suspect that AAP finishes configuring `AUTH_LDAP_GROUP_TYPE_PARAMS` sooner than `AUTH_LDAP_GROUP_TYPE`.

**Comment by rdrazny** [comment] 2022-10-20 08:23
Yeah, the role loops only once, but because the role uses async to process loop items, the order of processing is not completely deterministic. And as @ogajduse described, `AUTH_LDAP_GROUP_TYPE_PARAMS` can get applied before `AUTH_LDAP_GROUP_TYPE`, attempting to configure a setting that is not compatible with the current (at that point) `AUTH_LDAP_GROUP_TYPE`.

**Comment by djdanielsson** [comment] 2022-10-20 23:28
this may be a hard issue to reproduce often because it could be chance on the ordering of the objects and the speed it is processed. So it would be nice to get some more data. 1) how often can you reproduce this issue? 2) does changing the order in your settings list do anything? 3) what about removing the async?

**Comment by sean-m-sullivan** [comment] 2022-10-21 19:40
IMO it should be the same list all the time, as the Loop is 1x on the role task, and the actual loop all within python, as long as you are feeding the module a list. So that is what I'll look at.

**Comment by ivarmu** [comment] 2023-01-10 16:11
It's not related to the module, it's related to the async execution, that, as expected, is completely asynchronous. The following playbook shows that thing clearly:

```
---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    data:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
  tasks:
    - shell: |
        TIME_TO_SLEEP="$[ ( $RANDOM % 10 )  + 1 ]"
        echo "start time: $(date '+%M:%S.%N')"
        sleep ${TIME_TO_SLEEP}s
        echo "{{ item }} (sleeped ${TIME_TO_SLEEP}s)"
        echo "end time: $(date '+%M:%S.%N')"
      loop: "{{ data }}"
      async: 1000
      poll: 0
      register: setfact_res

    - name: "Configure Settings | Wait for finish the Settings creation"
      ansible.builtin.async_status:
        jid: "{{ item.ansible_job_id }}"
      register: __async_result
      until: __async_result.finished
      retries: 15
      delay: 1
      loop: "{{ setfact_res.results }}"

    - name: "debug 3"
      debug:
        msg: "{{ item.stdout_lines }}"
      loop: "{{ __async_result.results }}"
      loop_control:
        label: "{{ item.item.item }}"
...
```

It's output demonstrates that all the tasks are started at the same time:

```
ansible-playbook test2.yaml
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [localhost] *****************************************************************************************************************************************************************************************************************************

TASK [shell] *********************************************************************************************************************************************************************************************************************************
changed: [localhost] => (item=1)
changed: [localhost] => (item=2)
changed: [localhost] => (item=3)
changed: [localhost] => (item=4)
changed: [localhost] => (item=5)
changed: [localhost] => (item=6)
changed: [localhost] => (item=7)
changed: [localhost] => (item=8)
changed: [localhost] => (item=9)
changed: [localhost] => (item=10)
changed: [localhost] => (item=11)
changed: [localhost] => (item=12)
changed: [localhost] => (item=13)
changed: [localhost] => (item=14)
changed: [localhost] => (item=15)
changed: [localhost] => (item=16)
changed: [localhost] => (item=17)
changed: [localhost] => (item=18)
changed: [localhost] => (item=19)
changed: [localhost] => (item=20)

TASK [Configure Settings | Wait for finish the Settings creation] ****************************************************************************************************************************************************************************
FAILED - RETRYING: [localhost]: Configure Settings | Wait for finish the Settings creation (15 retries left).
FAILED - RETRYING: [localhost]: Configure Settings | Wait for finish the Settings creation (14 retries left).
changed: [localhost] => (item={'failed': 0, 'started': 1, 'finished': 0, 'ansible_job_id': '758318565071.2870744', 'results_file': '/home/ivan/.ansible_async/758318565071.2870744', 'changed': True, 'item': 1, 'ansible_loop_var': 'item'})
FAILED - RETRYING: [localhost]: Configure Settings | Wait for finish the Settings creation (15 retries left).
FAILED - RETRYING: [localhost]: Configure Settings | Wait for finish the Settings creation (14 retries left).
FAILED - RETRYING: [localhost]: Configure Settings | Wait for finish the Settings creation (13 retries left).
FAILED - RETRYING: [localhost]: Configure Settings | Wait for finish the Settings creation (12 retries left).
FAILED - RETRYING: [localhost]: Configure Settings | Wait for finish the Settings creation (11 retries left).
changed: [localhost] => (item={'failed': 0, 'started': 1, 'finished': 0, 'ansible_job_id': '233450376233.2870763', 'results_file': '/home/ivan/.ansible_async/233450376233.2870763', 'changed': True, 'item': 2, 'ansible_loop_var': 'item'})
changed: [localhost] => (item={'failed': 0, 'started': 1, 'finished': 0, 'ansible_job_id': '875530105734.2870784', 'results_file': '/home/ivan/.ansible_async/875530105734.2870784', 'changed': True, 'item': 3, 'ansible_loop_var': 'item'})
changed: [localhost] => (item={'failed': 0, 'started': 1, 'finished': 0, 'ansible_job_id': '461534508466.2870804', 'results_file': '/home/ivan/.ansible_async/461534508466.2870804', 'changed': True, 'item': 4, 'ansible_loop_var': 'item'})
changed: [localhost] => (item={'failed': 0, 'started': 1, 'finished': 0, 'ansible_job_id': '816390148078.2870825', 'results_file': '/home/ivan/.ansible_async/816390148078.2870825', 'changed': True, 'item': 5, 'ansible_loop_var': 'item'})
changed: [localhost] => (item={'failed': 0, 'started': 1, 'finished': 0, 'ansible_job_id': '311757295807.2870846', 'results_file': '/home/ivan/.ansible_async/311757295807.2870846', 'changed': True, 'item': 6, 'ansible_loop_var': 'item'})
changed: [localhost] => (item={'failed': 0, 'started': 1, 'finished': 0, 'ansible_job_id': '941615958004.2870866', 'results_file': '/home/ivan/.ansible_async/941615958004.2870866', 'changed': True, 'item': 7, 'ansible_loop_var': 'item'})
changed: [localhost] => (item={'failed': 0, 'started': 1, 'finished': 0, 'ansible_job_id': '565022597476.2870887', 'results_file': '/home/ivan/.ansible_async/565022597476.2870887', 'changed': True, 'item': 8, 'ansible_loop_var': 'item'})
changed: [localhost] => (item={'failed': 0, 'started': 1, 'finished': 0, 'ansible_job_id': '187562725451.2870907', 'results_file': '/home/ivan/.ansible_async/187562725451.2870907', 'changed': True, 'item': 9, 'ansible_loop_var': 'item'})
changed: [localhost] => (item={'failed': 0, 'started': 1, 'finished': 0, 'ansible_job_id': '732196383594.2870928', 'results_file': '/home/ivan/.ansible_async/732196383594.2870928', 'changed': True, 'item': 10, 'ansible_loop_var': 'item'})
changed: [localhost] => (item={'failed': 0, 'started': 1, 'finished': 0, 'ansible_job_id': '926490188350.2870949', 'results_file': '/home/ivan/.ansible_async/926490188350.2870949', 'changed': True, 'item': 11, 'ansible_loop_var': 'item'})
changed: [localhost] => (item={'failed': 0, 'started': 1, 'finished': 0, 'ansible_job_id': '830894815331.2870970', 'results_file': '/home/ivan/.ansible_async/830894815331.2870970', 'changed': True, 'item': 12, 'ansible_loop_var': 'item'})
changed: [localhost] => (item={'failed': 0, 'started': 1, 'finished': 0, 'ansible_job_id': '690726974140.2870991', 'results_file': '/home/ivan/.ansible_async/690726974140.2870991', 'changed': True, 'item': 13, 'ansible_loop_var': 'item'})
changed: [localhost] => (item={'failed': 0, 'started': 1, 'finished': 0, 'ansible_job_id': '501320841379.2871012', 'results_file': '/home/ivan/.ansible_async/501320841379.2871012', 'changed': True, 'item': 14, 'ansible_loop_var': 'item'})
changed: [localhost] => (item={'failed': 0, 'started': 1, 'finished': 0, 'ansible_job_id': '148293923872.2871033', 'results_file': '/home/ivan/.ansible_async/148293923872.2871033', 'changed': True, 'item': 15, 'ansible_loop_var': 'item'})
changed: [localhost] => (item={'failed': 0, 'started': 1, 'finished': 0, 'ansible_job_id': '19573067378.2871054', 'results_file': '/home/ivan/.ansible_async/19573067378.2871054', 'changed': True, 'item': 16, 'ansible_loop_var': 'item'})
changed: [localhost] => (item={'failed': 0, 'started': 1, 'finished': 0, 'ansible_job_id': '730297987404.2871074', 'results_file': '/home/ivan/.ansible_async/730297987404.2871074', 'changed': True, 'item': 17, 'ansible_loop_var': 'item'})
changed: [localhost] => (item={'failed': 0, 'started': 1, 'finished': 0, 'ansible_job_id': '937589070302.2871095', 'results_file': '/home/ivan/.ansible_async/937589070302.2871095', 'changed': True, 'item': 18, 'ansible_loop_var': 'item'})
changed: [localhost] => (item={'failed': 0, 'started': 1, 'finished': 0, 'ansible_job_id': '91901143771.2871116', 'results_file': '/home/ivan/.ansible_async/91901143771.2871116', 'changed': True, 'item': 19, 'ansible_loop_var': 'item'})
changed: [localhost] => (item={'failed': 0, 'started': 1, 'finished': 0, 'ansible_job_id': '800123311434.2871136', 'results_file': '/home/ivan/.ansible_async/800123311434.2871136', 'changed': True, 'item': 20, 'ansible_loop_var': 'item'})

TASK [debug 3] *******************************************************************************************************************************************************************************************************************************
ok: [localhost] => (item=1) => {
    "msg": [
        "start time: 58:50.058833726",
        "1 (sleeped 5s)",
        "end time: 58:55.062418353"
    ]
}
ok: [localhost] => (item=2) => {
    "msg": [
        "start time: 58:50.218955923",
        "2 (sleeped 10s)",
        "end time: 59:00.220278087"
    ]
}
ok: [localhost] => (item=3) => {
    "msg": [
        "start time: 58:50.372470570",
        "3 (sleeped 7s)",
        "end time: 58:57.374251194"
    ]
}
ok: [localhost] => (item=4) => {
    "msg": [
        "start time: 58:50.535257804",
        "4 (sleeped 8s)",
        "end time: 58:58.538811139"
    ]
}
ok: [localhost] => (item=5) => {
    "msg": [
        "start time: 58:50.691810295",
        "5 (sleeped 5s)",
        "end time: 58:55.693687573"
    ]
}
ok: [localhost] => (item=6) => {
    "msg": [
        "start time: 58:50.843006866",
        "6 (sleeped 1s)",
        "end time: 58:51.844461308"
    ]
}
ok: [localhost] => (item=7) => {
    "msg": [
        "start time: 58:51.000277317",
        "7 (sleeped 7s)",
        "end time: 58:58.002653533"
    ]
}
ok: [localhost] => (item=8) => {
    "msg": [
        "start time: 58:51.159251999",
        "8 (sleeped 3s)",
        "end time: 58:54.162929953"
    ]
}
ok: [localhost] => (item=9) => {
    "msg": [
        "start time: 58:51.320896524",
        "9 (sleeped 7s)",
        "end time: 58:58.324481614"
    ]
}
ok: [localhost] => (item=10) => {
    "msg": [
        "start time: 58:51.480256565",
        "10 (sleeped 10s)",
        "end time: 59:01.481570508"
    ]
}
ok: [localhost] => (item=11) => {
    "msg": [
        "start time: 58:51.637368965",
        "11 (sleeped 9s)",
        "end time: 59:00.639288629"
    ]
}
ok: [localhost] => (item=12) => {
    "msg": [
        "start time: 58:51.791044207",
        "12 (sleeped 7s)",
        "end time: 58:58.794687041"
    ]
}
ok: [localhost] => (item=13) => {
    "msg": [
        "start time: 58:51.948996402",
        "13 (sleeped 3s)",
        "end time: 58:54.952682146"
    ]
}
ok: [localhost] => (item=14) => {
    "msg": [
        "start time: 58:52.107685121",
        "14 (sleeped 8s)",
        "end time: 59:00.109155098"
    ]
}
ok: [localhost] => (item=15) => {
    "msg": [
        "start time: 58:52.263950656",
        "15 (sleeped 1s)",
        "end time: 58:53.265859393"
    ]
}
ok: [localhost] => (item=16) => {
    "msg": [
        "start time: 58:52.422941598",
        "16 (sleeped 2s)",
        "end time: 58:54.426345936"
    ]
}
ok: [localhost] => (item=17) => {
    "msg": [
        "start time: 58:52.580560249",
        "17 (sleeped 1s)",
        "end time: 58:53.584220340"
    ]
}
ok: [localhost] => (item=18) => {
    "msg": [
        "start time: 58:52.739476589",
        "18 (sleeped 8s)",
        "end time: 59:00.743110420"
    ]
}
ok: [localhost] => (item=19) => {
    "msg": [
        "start time: 58:52.893357736",
        "19 (sleeped 7s)",
        "end time: 58:59.897290147"
    ]
}
ok: [localhost] => (item=20) => {
    "msg": [
        "start time: 58:53.050896865",
        "20 (sleeped 8s)",
        "end time: 59:01.053799931"
    ]
}

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
localhost                  : ok=3    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

So @ogajduse is right with the error encountered, but I think the solution here could be so simple: call the role two times, one for all the settings needed to be created first, and another one for the others (or all of them all together). That way no modification is required for the role.

Another solution that requires the role to be modified, could be to implement the Async so it could be optional in function of the value of a defined variable for that role (`run_async: true/false`).

What are your thoughts @djdanielsson, @sean-m-sullivan and @Tompage1994?

**Comment by sean-m-sullivan** [comment] 2023-01-10 22:33
I am thinking of a better option, where we don't do lists,  and its a single call, give me a little time, looking at the API side.

**Comment by sean-m-sullivan** [comment] 2023-01-10 22:46
OK, I've looked at this, this is the solution
```
---
controller_settings:
  settings:
    AUTH_LDAP_SERVER_URI: "ldap://ldap.server.acme.com"
    AUTH_LDAP_USER_DN_TEMPLATE: "uid=%(user)s,ou=Users,dc=acme,dc=com"
    AUTH_LDAP_GROUP_SEARCH: 
      - 'dc=acme,dc=com'
      - 'SCOPE_SUBTREE'
      - '(objectClass=AcmeLdapGroup)'
    AUTH_LDAP_GROUP_TYPE: "GroupOfUniqueNamesType"
    AUTH_LDAP_USER_SEARCH:
      - OU=Users,DC=acme,DC=com
      - SCOPE_SUBTREE
      - "(cn=%(user)s)"
    AUTH_LDAP_START_TLS: true
    AUTH_LDAP_GROUP_TYPE_PARAMS: {}
...
```
The module is already built to accept and PATCH groups of settings. The Name/Value was left in for individual settings changes, and for legacy. 

This results in a single patch, an API request to GET current settings, does an update on the dataset, and then does a PATCH API call. 

This reduces the time it takes to do settings, Removes the asynchronous problem, and is just a better way of doing it overall. 

I am sorry I didn't recognize it beforehand. 

@ogajduse Let us know if this fixes the issue.

**Comment by sean-m-sullivan** [comment] 2023-01-10 22:54
Although looking at another thing, and figuring out why the ldap user search is having an error

**Comment by rdrazny** [comment] 2023-01-26 11:56
We have converted our config file to the format suggested by @sean-m-sullivan, and it seems to have fixed the issue (so far at least, as given the async nature of the call, the error was popping up only occasionally). But I believe this should fix things. Thank you guys for your help!

**Comment by sean-m-sullivan** [comment] 2023-01-29 04:10
Closing this as it looks to be fixed, Glad we could get that fixed!

**Closed as completed by sean-m-sullivan** 2023-01-29 04:10 UTC
Labels: question
